---
development:
  cloud_name: dc2atofzw
  api_key: '386177375969321'
  api_secret: VraU9FXBsW839pv2uqv7ISGj3W4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dc2atofzw
  api_key: '386177375969321'
  api_secret: VraU9FXBsW839pv2uqv7ISGj3W4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dc2atofzw
  api_key: '386177375969321'
  api_secret: VraU9FXBsW839pv2uqv7ISGj3W4
  enhance_image_tag: true
  static_image_support: false
